name: master

on:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
      with:
        swift-version: "5.6"
        
    - uses: actions/checkout@v2
      with:
        xcode-version: latest
        
    - name: install tuist
      run: curl -Ls https://install.tuist.io | bash
      
    - name: project Generate
      run: make generate
      
    - name: build
      run: tuist build
      
    - name: test
      run: tuist test
