name: pr

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: macos-12

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6.1"
        
    - uses: actions/checkout@v2
      with:
        xcode-version: latest
        
    - name: get Swift version
      run: swift --version
        
    - name: install tuist
      run: curl -Ls https://install.tuist.io | bash
      
    - name: project Generate
      run: |
        needle generate Projects/App/Sources/Application/NeedleGenerated.swift .
        make generate
      
    - name: build
      run: tuist build
      
    - name: test
      run: tuist test
